;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-dollar
        backward-kill-sexp
        backward-sentence
        backward-sexp
        beginning-of-defun
        c-electric-brace
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-end-of-defun
        c-indent-line-or-region
        cua-copy-region
        cua-cut-region
        cua-paste
        cua-scroll-up
        electric-newline-and-maybe-indent
        end-of-buffer
        flycheck-next-error
        forward-sexp
        fsharp-ac/electric-dot
        helm-M-x
        helm-show-kill-ring
        indent-for-tab-command
        kill-region
        live-delete-whitespace-except-one
        mark-defun
        markdown-exdent-or-delete
        org-delete-char
        suspend-frame
        toggle-input-method
        wdired-next-line
        wdired-previous-line
        ))

(setq mc/cmds-to-run-once
      '(
        ))
