;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-dollar
        backward-kill-sexp
        backward-sentence
        backward-sexp
        beginning-of-defun
        c-electric-brace
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-end-of-defun
        c-indent-line-or-region
        company-coq-maybe-exit-snippet
        cua-copy-region
        cua-cut-region
        cua-paste
        cua-scroll-up
        dumb-jump-go
        electric-newline-and-maybe-indent
        end-of-buffer
        flycheck-next-error
        forward-sexp
        fsharp-ac/electric-dot
        haskell-indentation-common-electric-command
        helm-M-x
        helm-show-kill-ring
        indent-for-tab-command
        intero-repl-load
        kill-region
        live-delete-whitespace-except-one
        mark-defun
        markdown-cycle
        markdown-exdent-or-delete
        org-delete-char
        paredit-backward
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-open-square
        pg-protected-undo
        sgml-slash
        suspend-frame
        toggle-input-method
        wdired-next-line
        wdired-previous-line
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        js2-mode-show-node
        mac-mwheel-scroll
        yas-expand
        ))
