;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-delete-word-or-kill-region
        forward-sexp
        haskell-mode-contextual-space
        outline-next-visible-heading
        ))

(setq mc/cmds-to-run-once
      '(
        ))
